const cards = [
  {
    id: 1,
    title: "HORIZONTE RESIDENCE",
    type: "Condomínio Fechado",
    city: "Barra Velha",
    neighborhood: "Tabuleiro",
    stage: "Emergente",
    src: "src/assets/cards/card_1.jpg",
    src2x: "src/assets/cards/card_1@2x.jpg",
  },
  {
    id: 2,
    title: "ONE TOWER",
    type: "Condomínio Fechado",
    city: "Barra Velha",
    neighborhood: "Pinheiros",
    stage: "Startup",
    src: "src/assets/cards/card_2.jpg",
    src2x: "src/assets/cards/card_2@2x.jpg",
  },
  {
    id: 3,
    title: "INFINITY COAST",
    type: "Casa",
    city: "Barra Velha",
    neighborhood: "Leblon",
    stage: "Estabelecida",
    src: "src/assets/cards/card_3.jpg",
    src2x: "src/assets/cards/card_3@2x.jpg",
  },
  {
    id: 4,
    title: "SKYLINE TOWER",
    type: "Apartamento de Cobertura",
    city: "Barra Velha",
    neighborhood: "Leblon",
    stage: "Emergente",
    src: "src/assets/cards/card_4.jpg",
    src2x: "src/assets/cards/card_4@2x.jpg",
  },
  {
    id: 5,
    title: "GRANDE PLACE TOWER",
    type: "Flat",
    city: "Barra Velha",
    neighborhood: "Cidade Jardim",
    stage: "Emergente",
    src: "src/assets/cards/card_5.jpg",
    src2x: "src/assets/cards/card_5@2x.jpg",
  },
  {
    id: 6,
    title: "IMPERIUM TOWER",
    type: "Flat",
    city: "Barra Velha",
    neighborhood: "Tabuleiro",
    stage: "Estabelecida",
    src: "src/assets/cards/card_6.jpg",
    src2x: "src/assets/cards/card_6@2x.jpg",
  },
  {
    id: 7,
    title: "TITANIUM TOWER",
    type: "Condomínio Fechado",
    city: "Barra Velha",
    neighborhood: "Pinheiros",
    stage: "Startup",
    src: "src/assets/cards/card_7.jpg",
    src2x: "src/assets/cards/card_7@2x.jpg",
  },
  {
    id: 8,
    title: "BLUE COST TOWER",
    type: "Casa",
    city: "Barra Velha",
    neighborhood: "Pinheiros",
    stage: "Emergente",
    src: "src/assets/cards/card_8.jpg",
    src2x: "src/assets/cards/card_8@2x.jpg",
  },
  {
    id: 9,
    title: "GRAND PLACE TOWER",
    type: "Condomínio Fechado",
    city: "Barra Velha",
    neighborhood: "Cidade Jardim",
    stage: "Estabelecida",
    src: "src/assets/cards/card_9.jpg",
    src2x: "src/assets/cards/card_9@2x.jpg",
  },
];

export default cards;
